### ISSUE TITLE
nodes can't resolve DNS names

### ISSUE THREAD

**Issue by pessoa** [rabbitmq/diy-kubernetes-examples#4]
On AWS EKS, I had to add:
```
        - name: RABBITMQ_USE_LONGNAME
          value: "true"
        - name: K8S_HOSTNAME_SUFFIX
          value: ".rabbitmq-headless.<namespace>.svc.cluster.local"
```
to the statefulset config to get node DNS names to resolve properly. Without this I would get just the hostname (eg. rabbitmq-1) and the other nodes can't resolve this.

Did I miss anything or this wasn't caught because replicas: 1 in the example?

**Comment by michaelklishin** [comment]
Hostname resolution can be set up differently by default on EKS vs. GKE or other hosted Kubernetes services. Not sure if we'd like to produce a complete EKS example if this is the only difference but it can be mentioned as an option in the README. Maybe someone would prefer to use FQDN-style node names on GKE.

**Comment by michaelklishin** [comment]
The only cluster node won't have to resolve names of any other nodes. Other examples provision [three nodes by default](https://github.com/rabbitmq/diy-kubernetes-examples/blob/3abfdeb5e6584d611e3523af2802cb04b5683337/kind/base/deployment.yaml#L10) so we would consider a PR that modifies the GKE one to do the same thing if needed.
