### ISSUE TITLE
Azure Kubernetes Service (AKS) Examples

### ISSUE THREAD

**Issue by markmcgookin** [rabbitmq/diy-kubernetes-examples#9]
As there are examples for Google etc here, it would be really useful to have a series of example files in place or documentation for deploying to Azure's AKS offering.

**Comment by michaelklishin** [comment]
You are welcome to contribute them. These examples were produced for a blog post and may be deprecated or removed any day. Our recommendation is the cluster Operator, which has [its own set of examples](https://github.com/rabbitmq/cluster-operator/tree/main/docs/examples).

**Comment by michaelklishin** [comment]
Our team has decided to archive this repository. DIY deployments is not where our focus is. If there is anything AKS-specific about deploying the [RabbitMQ Operator for Kubernetes](https://github.com/rabbitmq/cluster-operator/), please file a specific issue with your findings to that repo.
